name: Run Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Bharath !"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Run python Command
        run: |
          import platform
          print(platform.processor())
          print("Hello Bharath !")
        shell: python

  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
